In [20]:
import sys
import os
import numpy as np

In [13]:
categories = [ i.split('_')[1] for i in (os.listdir('jpegs_256_1/') + os.listdir('jpegs_256_2/') + os.listdir('jpegs_256_3/'))]

In [15]:
categories = set(categories)

In [22]:
categories

{'ApplyEyeMakeup',
 'ApplyLipstick',
 'Archery',
 'BabyCrawling',
 'BalanceBeam',
 'BandMarching',
 'BaseballPitch',
 'Basketball',
 'BasketballDunk',
 'BenchPress',
 'Biking',
 'Billiards',
 'BlowDryHair',
 'BlowingCandles',
 'BodyWeightSquats',
 'Bowling',
 'BoxingPunchingBag',
 'BoxingSpeedBag',
 'BreastStroke',
 'BrushingTeeth',
 'CleanAndJerk',
 'CliffDiving',
 'CricketBowling',
 'CricketShot',
 'CuttingInKitchen',
 'Diving',
 'Drumming',
 'Fencing',
 'FieldHockeyPenalty',
 'FloorGymnastics',
 'FrisbeeCatch',
 'FrontCrawl',
 'GolfSwing',
 'Haircut',
 'HammerThrow',
 'Hammering',
 'HandstandPushups',
 'HandstandWalking',
 'HeadMassage',
 'HighJump',
 'HorseRace',
 'HorseRiding',
 'HulaHoop',
 'IceDancing',
 'JavelinThrow',
 'JugglingBalls',
 'JumpRope',
 'JumpingJack',
 'Kayaking',
 'Knitting',
 'LongJump',
 'Lunges',
 'MilitaryParade',
 'Mixing',
 'MoppingFloor',
 'Nunchucks',
 'ParallelBars',
 'PizzaTossing',
 'PlayingCello',
 'PlayingDaf',
 'PlayingDhol',
 'PlayingFlute',
 'Play

In [29]:
num_categories = dict()
for file in (os.listdir('jpegs_256_1/') + os.listdir('jpegs_256_2/') + os.listdir('jpegs_256_3/')):
    cat = file.split('_')[1]
    if cat in num_categories.keys():
        num_categories[cat] += 1
    else:
        num_categories[cat] = 1

In [39]:
len(os.listdir('jpegs_256_1/')), len(os.listdir('jpegs_256_2/')), len(os.listdir('jpegs_256_3/')), len((os.listdir('jpegs_256_1/') + os.listdir('jpegs_256_2/') + os.listdir('jpegs_256_3/')))

(4296, 4812, 4212, 13320)

In [40]:
dirs = os.listdir('jpegs_256_1/') + os.listdir('jpegs_256_2/') + os.listdir('jpegs_256_3/')
dirs

['v_ApplyEyeMakeup_g01_c01',
 'v_ApplyEyeMakeup_g01_c02',
 'v_ApplyEyeMakeup_g01_c03',
 'v_ApplyEyeMakeup_g01_c04',
 'v_ApplyEyeMakeup_g01_c05',
 'v_ApplyEyeMakeup_g01_c06',
 'v_ApplyEyeMakeup_g02_c01',
 'v_ApplyEyeMakeup_g02_c02',
 'v_ApplyEyeMakeup_g02_c03',
 'v_ApplyEyeMakeup_g02_c04',
 'v_ApplyEyeMakeup_g03_c01',
 'v_ApplyEyeMakeup_g03_c02',
 'v_ApplyEyeMakeup_g03_c03',
 'v_ApplyEyeMakeup_g03_c04',
 'v_ApplyEyeMakeup_g03_c05',
 'v_ApplyEyeMakeup_g03_c06',
 'v_ApplyEyeMakeup_g04_c01',
 'v_ApplyEyeMakeup_g04_c02',
 'v_ApplyEyeMakeup_g04_c03',
 'v_ApplyEyeMakeup_g04_c04',
 'v_ApplyEyeMakeup_g04_c05',
 'v_ApplyEyeMakeup_g04_c06',
 'v_ApplyEyeMakeup_g04_c07',
 'v_ApplyEyeMakeup_g05_c01',
 'v_ApplyEyeMakeup_g05_c02',
 'v_ApplyEyeMakeup_g05_c03',
 'v_ApplyEyeMakeup_g05_c04',
 'v_ApplyEyeMakeup_g05_c05',
 'v_ApplyEyeMakeup_g05_c06',
 'v_ApplyEyeMakeup_g05_c07',
 'v_ApplyEyeMakeup_g06_c01',
 'v_ApplyEyeMakeup_g06_c02',
 'v_ApplyEyeMakeup_g06_c03',
 'v_ApplyEyeMakeup_g06_c04',
 'v_ApplyEyeMa

In [46]:
num_categories

{'ApplyEyeMakeup': 145,
 'ApplyLipstick': 114,
 'Archery': 145,
 'BabyCrawling': 132,
 'BalanceBeam': 108,
 'BandMarching': 155,
 'BaseballPitch': 150,
 'BasketballDunk': 131,
 'Basketball': 134,
 'BenchPress': 160,
 'Biking': 134,
 'Billiards': 150,
 'BlowDryHair': 131,
 'BlowingCandles': 109,
 'BodyWeightSquats': 112,
 'Bowling': 155,
 'BoxingPunchingBag': 163,
 'BoxingSpeedBag': 134,
 'BreastStroke': 101,
 'BrushingTeeth': 131,
 'CleanAndJerk': 112,
 'CliffDiving': 138,
 'CricketBowling': 139,
 'CricketShot': 167,
 'CuttingInKitchen': 110,
 'Diving': 150,
 'Drumming': 161,
 'Fencing': 111,
 'FieldHockeyPenalty': 126,
 'FloorGymnastics': 125,
 'FrisbeeCatch': 126,
 'FrontCrawl': 137,
 'GolfSwing': 139,
 'Haircut': 130,
 'Hammering': 140,
 'HammerThrow': 150,
 'HandstandPushups': 128,
 'HandstandWalking': 111,
 'HeadMassage': 147,
 'HighJump': 123,
 'HorseRace': 124,
 'HorseRiding': 164,
 'HulaHoop': 125,
 'IceDancing': 158,
 'JavelinThrow': 117,
 'JugglingBalls': 121,
 'JumpingJack':

In [33]:
folder_names = []
for cat in num_categories.keys():
    folder_names = folder_names + [ 'v_' + cat + '_' + str(i) for i in range(num_categories[cat])]

In [38]:
len(folder_names), folder_names

(13320,
 ['v_ApplyEyeMakeup_0',
  'v_ApplyEyeMakeup_1',
  'v_ApplyEyeMakeup_2',
  'v_ApplyEyeMakeup_3',
  'v_ApplyEyeMakeup_4',
  'v_ApplyEyeMakeup_5',
  'v_ApplyEyeMakeup_6',
  'v_ApplyEyeMakeup_7',
  'v_ApplyEyeMakeup_8',
  'v_ApplyEyeMakeup_9',
  'v_ApplyEyeMakeup_10',
  'v_ApplyEyeMakeup_11',
  'v_ApplyEyeMakeup_12',
  'v_ApplyEyeMakeup_13',
  'v_ApplyEyeMakeup_14',
  'v_ApplyEyeMakeup_15',
  'v_ApplyEyeMakeup_16',
  'v_ApplyEyeMakeup_17',
  'v_ApplyEyeMakeup_18',
  'v_ApplyEyeMakeup_19',
  'v_ApplyEyeMakeup_20',
  'v_ApplyEyeMakeup_21',
  'v_ApplyEyeMakeup_22',
  'v_ApplyEyeMakeup_23',
  'v_ApplyEyeMakeup_24',
  'v_ApplyEyeMakeup_25',
  'v_ApplyEyeMakeup_26',
  'v_ApplyEyeMakeup_27',
  'v_ApplyEyeMakeup_28',
  'v_ApplyEyeMakeup_29',
  'v_ApplyEyeMakeup_30',
  'v_ApplyEyeMakeup_31',
  'v_ApplyEyeMakeup_32',
  'v_ApplyEyeMakeup_33',
  'v_ApplyEyeMakeup_34',
  'v_ApplyEyeMakeup_35',
  'v_ApplyEyeMakeup_36',
  'v_ApplyEyeMakeup_37',
  'v_ApplyEyeMakeup_38',
  'v_ApplyEyeMakeup_39',
  

In [42]:
for i in range(13320):
    path = 'jpegs_256_'
    if i<4296:
        path = path + '1/'
    elif i<9108:
        path = path + '2/'
    else:
        path = path + '3/'
    os.rename(path + dirs[i], path + folder_names[i])

In [37]:
os.rename('Newfolder', 'New')

In [92]:
data = []
labels = []
for i in range(101):
    cat = list(num_categories.keys())[i]
    num = num_categories[cat] + 200*i
    labels = labels + list(np.ones(num_categories[cat])*(num//200))
    data.append(np.array(range(200*i, num)))
labels = [int(i) for i in labels]

In [93]:
data = np.hstack(data)
len(data), data

(13320, array([    0,     1,     2, ..., 20125, 20126, 20127]))

In [126]:
labels = np.array(labels)

In [95]:
from sklearn.model_selection import train_test_split

In [100]:
train, test = train_test_split(np.array(range(13320)), test_size = 0.1, shuffle = True)

In [128]:
X_train = data[train]
X_test = data[test]
y_train = labels[train]
y_test = labels[test]

In [108]:
X_train//200, X_train%200

(array([46, 20, 93, ..., 29, 93, 96], dtype=int32),
 array([ 66,  40, 116, ..., 110,  96,  72], dtype=int32))

In [129]:
Requirements = [num_categories, folder_names, X_train, y_train, X_test, y_test]

In [130]:
import pickle
pickle.dump(Requirements, open('Data.p', 'wb'))

In [131]:
Req = pickle.load(open('Data.p', 'rb'))

In [132]:
Req

[{'ApplyEyeMakeup': 145,
  'ApplyLipstick': 114,
  'Archery': 145,
  'BabyCrawling': 132,
  'BalanceBeam': 108,
  'BandMarching': 155,
  'BaseballPitch': 150,
  'BasketballDunk': 131,
  'Basketball': 134,
  'BenchPress': 160,
  'Biking': 134,
  'Billiards': 150,
  'BlowDryHair': 131,
  'BlowingCandles': 109,
  'BodyWeightSquats': 112,
  'Bowling': 155,
  'BoxingPunchingBag': 163,
  'BoxingSpeedBag': 134,
  'BreastStroke': 101,
  'BrushingTeeth': 131,
  'CleanAndJerk': 112,
  'CliffDiving': 138,
  'CricketBowling': 139,
  'CricketShot': 167,
  'CuttingInKitchen': 110,
  'Diving': 150,
  'Drumming': 161,
  'Fencing': 111,
  'FieldHockeyPenalty': 126,
  'FloorGymnastics': 125,
  'FrisbeeCatch': 126,
  'FrontCrawl': 137,
  'GolfSwing': 139,
  'Haircut': 130,
  'Hammering': 140,
  'HammerThrow': 150,
  'HandstandPushups': 128,
  'HandstandWalking': 111,
  'HeadMassage': 147,
  'HighJump': 123,
  'HorseRace': 124,
  'HorseRiding': 164,
  'HulaHoop': 125,
  'IceDancing': 158,
  'JavelinThrow'

In [127]:
labels[[1, 2]]

array([0, 0])

In [144]:
count = 0
for cat in num_categories.keys():
    for i in range(num_categories[cat]):
        os.rename('jpegs_256/' + cat + '_' + str(i), 'jpegs_256/' + cat + '_' + str(data[count]))
        count += 1